plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.advanceseeds.coreml'
version = '0.1.0'

android {
  namespace "com.advanceseeds.coreml"
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  sourceSets {
    main {
      assets.srcDirs += ['../../../assets/models']
    }
  }
}

dependencies {
  implementation "androidx.camera:camera-core:1.5.0-alpha03"
  implementation project(":react-native-vision-camera")
  implementation "com.google.ai.edge.litert:litert:1.4.0"
  implementation "com.google.ai.edge.litert:litert-gpu:1.4.0"
  implementation "com.google.ai.edge.litert:litert-gpu-api:1.4.0"
}
