apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.advanceseeds.coreml'
version = '0.1.0'

android {
  namespace 'com.advanceseeds.coreml'
  compileSdkVersion safeExtGet('compileSdkVersion', 35)
  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 24)
    targetSdkVersion safeExtGet('targetSdkVersion', 35)
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions { jvmTarget = '17' }
}

dependencies {
  implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.0.21'
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
