// PLACEHOLDER — generated by `pnpm supabase:types` after the schema lands.
// Until then this file is intentionally empty so consumers can import without
// errors. Once supabase/migrations/* is applied, run:
//
//   pnpm supabase:types
//
// which writes a Database type with Row/Insert/Update aliases per table.

export type Database = Record<string, never>;
